document.documentElement.dataset.ready='starting';
window.addEventListener('error',e=>{document.documentElement.dataset.ready='error';document.documentElement.dataset.error=String(e.error||e.message||'unknown');});
window.addEventListener('unhandledrejection',e=>{document.documentElement.dataset.ready='error';document.documentElement.dataset.error=String(e.reason||'unhandled rejection');});

import * as THREE from 'three/webgpu';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {attribute,clamp,color,mix,normalWorld,positionWorld,smoothstep,uniform,texture,uv} from 'three/tsl';
import {buildDesertMuseum} from './tree_gold_dense.js';
import {DESERT_MUSEUM_PALO_VERDE,validateSpeciesRecipe} from './recipes.js';

const recipe=DESERT_MUSEUM_PALO_VERDE;validateSpeciesRecipe(recipe);
const canvas=document.querySelector('#viewport');const renderer=new THREE.WebGPURenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.8));renderer.setSize(window.innerWidth,window.innerHeight,false);await renderer.init();
const scene=new THREE.Scene();scene.background=new THREE.Color(recipe.material.sky);scene.fog=new THREE.FogExp2(recipe.material.sky,.0055);
const camera=new THREE.PerspectiveCamera(42,window.innerWidth/window.innerHeight,.08,120);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=4.0;controls.maxDistance=28;controls.maxPolarAngle=Math.PI*.49;
const sunDirection=uniform(new THREE.Vector3(-.45,.78,.43).normalize());

function rand(seed){let s=seed>>>0||1;return()=>{s=Math.imul(1664525,s)+1013904223>>>0;return s/4294967296;};}
function makeAtlas(){const c=document.createElement('canvas');c.width=1024;c.height=256;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);for(let tile=0;tile<4;tile++){const r=rand(7109+tile*1943),ox=tile*256;ctx.save();ctx.beginPath();ctx.rect(ox,0,256,256);ctx.clip();for(let i=0;i<8;i++){const a=r()*Math.PI*2,rr=Math.pow(r(),.82)*48,cx=ox+128+Math.cos(a)*rr,cy=128+Math.sin(a)*rr*.54,len=68+r()*52,wid=42+r()*40,rot=(r()-.5)*1.45,val=Math.round(194+r()*46);ctx.save();ctx.translate(cx,cy);ctx.rotate(rot);ctx.globalAlpha=.90+r()*.10;ctx.fillStyle=`rgb(${val},${val},${val})`;ctx.beginPath();ctx.ellipse(0,0,len*.5,wid*.5,0,0,Math.PI*2);ctx.fill();ctx.restore();}for(let i=0;i<9;i++){const a=r()*Math.PI*2,rr=73+r()*22,cx=ox+128+Math.cos(a)*rr,cy=128+Math.sin(a)*rr*.55,len=30+r()*30,wid=17+r()*20,val=Math.round(190+r()*48);ctx.save();ctx.translate(cx,cy);ctx.rotate(a+(r()-.5)*.72);ctx.globalAlpha=.82+r()*.16;ctx.fillStyle=`rgb(${val},${val},${val})`;ctx.beginPath();ctx.ellipse(0,0,len*.5,wid*.5,0,0,Math.PI*2);ctx.fill();ctx.restore();}ctx.globalCompositeOperation='destination-out';for(let h=0;h<3;h++){const a=r()*Math.PI*2,rr=22+r()*44;ctx.globalAlpha=.58+r()*.20;ctx.beginPath();ctx.ellipse(ox+128+Math.cos(a)*rr,128+Math.sin(a)*rr*.48,7+r()*9,5+r()*7,r()*Math.PI,0,Math.PI*2);ctx.fill();}ctx.globalCompositeOperation='source-over';ctx.restore();}const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.NoColorSpace;tex.needsUpdate=true;return tex;}
const atlas=makeAtlas();
function illustratedMaterial(palette,role,masked=false){const m=new THREE.MeshBasicNodeMaterial({side:THREE.DoubleSide}),shadow=color(palette[0]),middle=color(palette[1]),light=color(palette[2]),variation=attribute('variation','float').sub(.5).mul(role==='foliage'?.018:.014),height=clamp(positionWorld.y.div(recipe.growth.mature.heightM+.4),0,1),dot=normalWorld.dot(sunDirection),facing=dot.mul(role==='foliage'?.28:.34).add(role==='foliage'?.57:.55);let value=facing.add(normalWorld.y.mul(role==='foliage'?.016:.010)).add(height.mul(role==='foliage'?.020:.010)).add(variation);if(masked){const sample=texture(atlas,uv());m.opacityNode=sample.a;m.alphaTest=.23;value=value.add(sample.r.sub(.82).mul(.045));}const mid=smoothstep(.43,.53,value),hi=smoothstep(.76,.88,value);m.colorNode=mix(mix(shadow,middle,mid),light,hi);m.roughness=1;return m;}
const materials={wood:illustratedMaterial(['#71957f','#8ca891','#b1c2ad'],'wood'),foliage:illustratedMaterial(['#62784f','#83965d','#a8b675'],'foliage',true),flowers:illustratedMaterial(recipe.material.bloom,'bloom',true),outline:new THREE.MeshBasicNodeMaterial({color:new THREE.Color('#71877c'),side:THREE.BackSide})};
const ground=new THREE.Mesh(new THREE.PlaneGeometry(60,60),new THREE.MeshBasicNodeMaterial({color:new THREE.Color('#e0d5c1')}));ground.rotation.x=-Math.PI/2;ground.position.y=-.025;scene.add(ground);
function shadowTexture(){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d'),g=x.createRadialGradient(128,128,6,128,128,126);g.addColorStop(0,'rgba(74,79,67,.28)');g.addColorStop(.55,'rgba(74,79,67,.10)');g.addColorStop(1,'rgba(74,79,67,0)');x.fillStyle=g;x.fillRect(0,0,256,256);return new THREE.CanvasTexture(c);}
const shadowMat=new THREE.MeshBasicMaterial({map:shadowTexture(),transparent:true,depthWrite:false,opacity:.40,color:new THREE.Color('#77796f')}),contactShadow=new THREE.Mesh(new THREE.PlaneGeometry(1,1),shadowMat);contactShadow.rotation.x=-Math.PI/2;contactShadow.rotation.z=-.16;contactShadow.position.set(.28,.004,.05);scene.add(contactShadow);
const state={seed:41,maturity:1,openness:1,density:1,sprayScale:1,bloom:.10,azimuth:-35,elevation:52,shadow:4.5};let treeGroup=null,flowerMesh=null,flowerIndexCount=0,currentReport=null,timer=null;
function backendLabel(){const n=renderer.backend?.constructor?.name||'Renderer';return/webgpu/i.test(n)?'WebGPU':/webgl/i.test(n)?'WebGL2 fallback':n;}
function disposeTree(){if(!treeGroup)return;treeGroup.traverse(o=>{if(o.isMesh&&o.geometry)o.geometry.dispose();});scene.remove(treeGroup);}
function rebuildTree(){disposeTree();const built=buildDesertMuseum({seed:state.seed,maturity:state.maturity,openness:state.openness,density:state.density,sprayScale:state.sprayScale},recipe);treeGroup=new THREE.Group();const outline=new THREE.Mesh(built.outline,materials.outline),wood=new THREE.Mesh(built.wood,materials.wood),foliage=new THREE.Mesh(built.foliage,materials.foliage);treeGroup.add(outline,wood,foliage);flowerMesh=new THREE.Mesh(built.flowers,materials.flowers);flowerIndexCount=built.flowers.index?.count??0;treeGroup.add(flowerMesh);scene.add(treeGroup);currentReport=built.report;setBloom(state.bloom);updateMetrics();updateShadow();window.__PALO_VERDE_REPORT__={...currentReport,backend:backendLabel(),errors:[],artApproved:false,recipeDriven:true,paintedContactShadow:true,foliageAtlasTiles:4,target:'anime-background Desert Museum palo verde LOD0',goldComposition:true};document.documentElement.dataset.report=JSON.stringify(window.__PALO_VERDE_REPORT__);}
function setBloom(v){state.bloom=Number(v);if(flowerMesh?.geometry?.index&&currentReport?.flowerBrushes){const per=flowerIndexCount/currentReport.flowerBrushes,visible=Math.floor(currentReport.flowerBrushes*state.bloom);flowerMesh.geometry.setDrawRange(0,Math.floor(visible*per));flowerMesh.visible=visible>0;}else if(flowerMesh)flowerMesh.visible=false;const o=document.querySelector('#bloomOut');if(o)o.value=`${Math.round(state.bloom*100)}%`;}
function updateSun(){const az=THREE.MathUtils.degToRad(state.azimuth),el=THREE.MathUtils.degToRad(state.elevation);sunDirection.value.set(Math.cos(el)*Math.cos(az),Math.sin(el),Math.cos(el)*Math.sin(az)).normalize();}
function updateShadow(){const soft=THREE.MathUtils.clamp(state.shadow,.5,5),spread=currentReport?.targetSpreadM||recipe.growth.mature.spreadM;contactShadow.scale.set(spread*(.69+soft*.034),spread*(.38+soft*.023),1);shadowMat.opacity=THREE.MathUtils.lerp(.44,.24,(soft-.5)/4.5);}
function updateMetrics(){document.querySelector('#backend').textContent=backendLabel();document.querySelector('#triangles').textContent=currentReport?Math.round(currentReport.triangles).toLocaleString():'—';document.querySelector('#brushes').textContent=currentReport?currentReport.foliageBrushes.toLocaleString():'—';}
function schedule(){clearTimeout(timer);timer=setTimeout(rebuildTree,40);}
const bindings={seed:{out:v=>String(Math.round(v)),rebuild:true},maturity:{out:v=>`${Math.round(v*100)}%`,rebuild:true},openness:{out:v=>v.toFixed(2),rebuild:true},density:{out:v=>v.toFixed(2),rebuild:true},spray:{key:'sprayScale',out:v=>v.toFixed(2),rebuild:true},bloom:{out:v=>`${Math.round(v*100)}%`,change:setBloom},azimuth:{out:v=>`${Math.round(v)}°`,change:updateSun},elevation:{out:v=>`${Math.round(v)}°`,change:updateSun},shadow:{out:v=>v.toFixed(1),change:updateShadow}};for(const[id,b]of Object.entries(bindings)){const input=document.querySelector(`#${id}`),o=document.querySelector(`#${id}Out`);if(!input)continue;const key=b.key||id;if(state[key]!==undefined)input.value=String(state[key]);if(o)o.value=b.out(state[key]);input.addEventListener('input',()=>{state[key]=Number(input.value);if(o)o.value=b.out(state[key]);if(b.change)b.change(state[key]);if(b.rebuild)schedule();});}
const views={hero:{position:[6.8,4.9,7.35],target:[0,3.25,0]},side:{position:[-7.7,4.55,.7],target:[0,3.15,0]},low:{position:[5.4,2.35,6.65],target:[0,3.35,0]},elevated:{position:[5.9,7.9,6.1],target:[0,3.2,0]},reverse:{position:[-6.7,4.9,-7.55],target:[0,3.25,0]}};function setView(name){const v=views[name];if(!v)return;camera.position.fromArray(v.position);controls.target.fromArray(v.target);controls.update();}for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>setView(b.dataset.view));document.querySelector('#randomize').addEventListener('click',()=>{state.seed=1+Math.floor(Math.random()*998);document.querySelector('#seed').value=String(state.seed);document.querySelector('#seedOut').value=String(state.seed);rebuildTree();});
updateSun();rebuildTree();setView('hero');document.documentElement.dataset.ready='true';let frames=0,start=performance.now(),smooth=60;function animate(now){controls.update();renderer.render(scene,camera);frames++;if(now-start>600){const fps=frames*1000/(now-start);smooth=smooth*.4+fps*.6;document.querySelector('#fps').textContent=smooth.toFixed(0);frames=0;start=now;}}renderer.setAnimationLoop(animate);window.addEventListener('resize',()=>{camera.aspect=window.innerWidth/window.innerHeight;camera.updateProjectionMatrix();renderer.setSize(window.innerWidth,window.innerHeight,false);});const q=new URLSearchParams(location.search);if(q.has('capture')){document.querySelector('#panel').style.display='none';document.querySelector('#badge').style.display='none';setView(q.get('view')||'hero');}
