document.documentElement.dataset.ready='starting';
window.addEventListener('error',e=>{document.documentElement.dataset.ready='error';document.documentElement.dataset.error=String(e.error||e.message||'unknown');});
window.addEventListener('unhandledrejection',e=>{document.documentElement.dataset.ready='error';document.documentElement.dataset.error=String(e.reason||'unhandled rejection');});

import * as THREE from 'three/webgpu';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {attribute,clamp,color,mix,normalWorld,positionWorld,smoothstep,uniform,texture,uv} from 'three/tsl';
import {buildAuthoredDesertMuseum} from './tree_authored.js';
import {DESERT_MUSEUM_PALO_VERDE,validateSpeciesRecipe} from './recipes.js';
import {DESERT_MUSEUM_HERO_TEMPLATE,validateHeroTemplate} from './palo_verde_authored_template.js';
const recipe=DESERT_MUSEUM_PALO_VERDE,template=DESERT_MUSEUM_HERO_TEMPLATE;validateSpeciesRecipe(recipe);validateHeroTemplate(template);

const canvas=document.querySelector('#viewport'),renderer=new THREE.WebGPURenderer({canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.8));renderer.setSize(window.innerWidth,window.innerHeight,false);await renderer.init();
const scene=new THREE.Scene();scene.background=new THREE.Color('#e1ebe8');scene.fog=new THREE.FogExp2('#e1ebe8',.0048);const camera=new THREE.PerspectiveCamera(41,window.innerWidth/window.innerHeight,.08,120),controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=4;controls.maxDistance=28;controls.maxPolarAngle=Math.PI*.49;const sunDirection=uniform(new THREE.Vector3(-.45,.78,.43).normalize());
function rng(seed){let s=seed>>>0||1;return()=>{s=Math.imul(1664525,s)+1013904223>>>0;return s/4294967296;};}
function ellipse(ctx,x,y,rx,ry,rot,gray,alpha=1){ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.globalAlpha=alpha;ctx.fillStyle=`rgb(${gray},${gray},${gray})`;ctx.beginPath();ctx.ellipse(0,0,rx,ry,0,0,Math.PI*2);ctx.fill();ctx.restore();}
function makeAtlas(){const c=document.createElement('canvas');c.width=1024;c.height=256;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);for(let tile=0;tile<4;tile++){const r=rng(29131+tile*5119),ox=tile*256;ctx.save();ctx.beginPath();ctx.rect(ox,0,256,256);ctx.clip();for(let i=0;i<7;i++){const a=r()*Math.PI*2,rr=Math.pow(r(),.84)*44;ellipse(ctx,ox+118+Math.cos(a)*rr,139+Math.sin(a)*rr*.50,39+r()*30,24+r()*22,(r()-.5)*1.18,96+Math.round(r()*26),.97);}for(let i=0;i<7;i++){const a=r()*Math.PI*2,rr=Math.pow(r(),.84)*42;ellipse(ctx,ox+132+Math.cos(a)*rr,121+Math.sin(a)*rr*.48,36+r()*27,21+r()*20,(r()-.5)*1.16,157+Math.round(r()*24),.97);}for(let i=0;i<3;i++){const a=-.45+r()*.90,rr=24+r()*34;ellipse(ctx,ox+136+Math.cos(a)*rr,101+Math.sin(a)*rr*.40,23+r()*20,13+r()*14,(r()-.5)*.78,216+Math.round(r()*22),.93);}for(let i=0;i<7;i++){const a=r()*Math.PI*2,rr=74+r()*21;ellipse(ctx,ox+128+Math.cos(a)*rr,128+Math.sin(a)*rr*.53,17+r()*15,8+r()*9,a+(r()-.5)*.62,142+Math.round(r()*40),.88);}ctx.globalCompositeOperation='destination-out';for(let h=0;h<3;h++){const a=r()*Math.PI*2,rr=22+r()*42;ctx.globalAlpha=.68;ctx.beginPath();ctx.ellipse(ox+128+Math.cos(a)*rr,128+Math.sin(a)*rr*.47,7+r()*9,5+r()*7,r()*Math.PI,0,Math.PI*2);ctx.fill();}ctx.globalCompositeOperation='source-over';ctx.restore();}const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.NoColorSpace;tex.needsUpdate=true;return tex;}
const atlas=makeAtlas();
function woodMaterial(){const m=new THREE.MeshBasicNodeMaterial({side:THREE.DoubleSide}),shadow=color('#6e907b'),mid=color('#8ca78f'),light=color('#b4c5b1'),variation=attribute('variation','float').sub(.5).mul(.012),value=normalWorld.dot(sunDirection).mul(.16).add(.59).add(variation).add(clamp(positionWorld.y.div(8),0,1).mul(.010));m.colorNode=mix(mix(shadow,mid,smoothstep(.46,.55,value)),light,smoothstep(.78,.90,value));m.roughness=1;return m;}
function foliageMaterial(palette){const m=new THREE.MeshBasicNodeMaterial({side:THREE.DoubleSide}),sample=texture(atlas,uv()),shadow=color(palette[0]),mid=color(palette[1]),light=color(palette[2]),region=attribute('variation','float').sub(.5).mul(.34),painted=sample.r.sub(.50).mul(.46),form=normalWorld.dot(sunDirection).mul(.075).add(.545),height=clamp(positionWorld.y.div(8),0,1).mul(.008),value=form.add(painted).add(region).add(height);m.opacityNode=sample.a;m.alphaTest=.21;m.colorNode=mix(mix(shadow,mid,smoothstep(.44,.53,value)),light,smoothstep(.71,.80,value));m.roughness=1;return m;}
const materials={wood:woodMaterial(),foliage:foliageMaterial(['#526948','#7b905b','#a5b675']),flowers:foliageMaterial(['#9d8037','#c2a649','#dec866']),outline:new THREE.MeshBasicNodeMaterial({color:new THREE.Color('#758b80'),side:THREE.BackSide})};
const ground=new THREE.Mesh(new THREE.PlaneGeometry(60,60),new THREE.MeshBasicNodeMaterial({color:new THREE.Color('#e2d8c7')}));ground.rotation.x=-Math.PI/2;ground.position.y=-.025;scene.add(ground);function contactTexture(){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d'),g=x.createRadialGradient(128,128,5,128,128,126);g.addColorStop(0,'rgba(70,76,65,.24)');g.addColorStop(.58,'rgba(70,76,65,.075)');g.addColorStop(1,'rgba(70,76,65,0)');x.fillStyle=g;x.fillRect(0,0,256,256);return new THREE.CanvasTexture(c);}const shadowMat=new THREE.MeshBasicMaterial({map:contactTexture(),transparent:true,depthWrite:false,opacity:.32,color:new THREE.Color('#787b71')}),contactShadow=new THREE.Mesh(new THREE.PlaneGeometry(1,1),shadowMat);contactShadow.rotation.x=-Math.PI/2;contactShadow.rotation.z=-.14;contactShadow.position.set(.22,.004,.03);scene.add(contactShadow);
const state={seed:41,maturity:1,openness:1,density:1,bloom:.12,azimuth:-35,elevation:52,shadow:4.7};let group=null,flowerMesh=null,currentReport=null,timer=null;function backendLabel(){const n=renderer.backend?.constructor?.name||'Renderer';return/webgpu/i.test(n)?'WebGPU':/webgl/i.test(n)?'WebGL2 fallback':n;}function dispose(){if(!group)return;group.traverse(o=>{if(o.isMesh&&o.geometry)o.geometry.dispose();});scene.remove(group);}function rebuild(){dispose();const built=buildAuthoredDesertMuseum(state,recipe,template);group=new THREE.Group();group.add(new THREE.Mesh(built.outline,materials.outline),new THREE.Mesh(built.wood,materials.wood),new THREE.Mesh(built.foliage,materials.foliage));flowerMesh=new THREE.Mesh(built.flowers,materials.flowers);group.add(flowerMesh);scene.add(group);currentReport=built.report;flowerMesh.visible=state.bloom>.02;updateMetrics();updateShadow();window.__PALO_VERDE_REPORT__={...currentReport,backend:backendLabel(),errors:[],artApproved:false,recipeDriven:true,authoredTemplate:true,paintedToneAtlas:true,paintedContactShadow:true,foliageAtlasTiles:4,target:'anime-background Desert Museum palo verde LOD0'};document.documentElement.dataset.report=JSON.stringify(window.__PALO_VERDE_REPORT__);}function updateMetrics(){document.querySelector('#backend').textContent=backendLabel();document.querySelector('#triangles').textContent=currentReport?Math.round(currentReport.triangles).toLocaleString():'—';document.querySelector('#brushes').textContent=currentReport?currentReport.foliageMasses.toLocaleString():'—';}
function updateSun(){const az=THREE.MathUtils.degToRad(state.azimuth),el=THREE.MathUtils.degToRad(state.elevation);sunDirection.value.set(Math.cos(el)*Math.cos(az),Math.sin(el),Math.cos(el)*Math.sin(az)).normalize();}function updateShadow(){const spread=currentReport?.targetSpreadM||recipe.growth.mature.spreadM,soft=THREE.MathUtils.clamp(state.shadow,.5,5);contactShadow.scale.set(spread*(.69+soft*.032),spread*(.38+soft*.020),1);shadowMat.opacity=THREE.MathUtils.lerp(.36,.18,(soft-.5)/4.5);}function schedule(){clearTimeout(timer);timer=setTimeout(rebuild,35);}const bindings={seed:{out:v=>String(Math.round(v)),rebuild:true},maturity:{out:v=>`${Math.round(v*100)}%`,rebuild:true},openness:{out:v=>v.toFixed(2),rebuild:true},density:{out:v=>v.toFixed(2),rebuild:true},bloom:{out:v=>`${Math.round(v*100)}%`,rebuild:true},azimuth:{out:v=>`${Math.round(v)}°`,change:updateSun},elevation:{out:v=>`${Math.round(v)}°`,change:updateSun},shadow:{out:v=>v.toFixed(1),change:updateShadow}};for(const[id,b]of Object.entries(bindings)){const input=document.querySelector(`#${id}`),o=document.querySelector(`#${id}Out`);if(!input)continue;if(state[id]!==undefined)input.value=String(state[id]);if(o)o.value=b.out(state[id]);input.addEventListener('input',()=>{state[id]=Number(input.value);if(o)o.value=b.out(state[id]);if(b.change)b.change(state[id]);if(b.rebuild)schedule();});}
const views={hero:{position:[6.75,4.85,7.25],target:[0,3.35,0]},side:{position:[-7.55,4.55,.65],target:[0,3.28,0]},low:{position:[5.35,2.35,6.55],target:[0,3.50,0]},elevated:{position:[5.85,7.65,6.00],target:[0,3.35,0]},reverse:{position:[-6.65,4.85,-7.45],target:[0,3.35,0]}};function setView(name){const v=views[name];if(!v)return;camera.position.fromArray(v.position);controls.target.fromArray(v.target);controls.update();}for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>setView(b.dataset.view));document.querySelector('#randomize').addEventListener('click',()=>{state.seed=1+Math.floor(Math.random()*998);document.querySelector('#seed').value=String(state.seed);document.querySelector('#seedOut').value=String(state.seed);rebuild();});updateSun();rebuild();setView('hero');document.documentElement.dataset.ready='true';let frames=0,start=performance.now(),smooth=60;function animate(now){controls.update();renderer.render(scene,camera);frames++;if(now-start>600){const fps=frames*1000/(now-start);smooth=smooth*.4+fps*.6;document.querySelector('#fps').textContent=smooth.toFixed(0);frames=0;start=now;}}renderer.setAnimationLoop(animate);window.addEventListener('resize',()=>{camera.aspect=window.innerWidth/window.innerHeight;camera.updateProjectionMatrix();renderer.setSize(window.innerWidth,window.innerHeight,false);});const q=new URLSearchParams(location.search);if(q.has('capture')){document.querySelector('#panel').style.display='none';document.querySelector('#badge').style.display='none';setView(q.get('view')||'hero');}
