import * as THREE from 'three/webgpu';
import { DESERT_MUSEUM_PALO_VERDE, resolveGrowth, validateSpeciesRecipe } from './recipes.js';
import { DESERT_MUSEUM_HERO_TEMPLATE, validateHeroTemplate } from './palo_verde_authored_template.js';

const UP=new THREE.Vector3(0,1,0),X=new THREE.Vector3(1,0,0),GOLDEN=Math.PI*(3-Math.sqrt(5));
class RNG{constructor(seed=41){this.state=seed>>>0||1;}next(){let t=this.state+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;}range(a,b){return a+(b-a)*this.next();}signed(v=1){return this.range(-v,v);}}
function hash(seed,label){let h=seed>>>0;for(let i=0;i<label.length;i++)h=Math.imul(h^label.charCodeAt(i),16777619)>>>0;return h||1;}
function bucket(){return{positions:[],normals:[],variation:[],uv:[],indices:[]};}
function geometry(d){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(d.positions,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(d.normals,3));g.setAttribute('variation',new THREE.Float32BufferAttribute(d.variation,1));g.setAttribute('uv',new THREE.Float32BufferAttribute(d.uv,2));g.setIndex(d.indices);g.computeBoundingBox();g.computeBoundingSphere();return g;}
function vertex(out,p,n,v,u=0,w=0){out.positions.push(p.x,p.y,p.z);out.normals.push(n.x,n.y,n.z);out.variation.push(v);out.uv.push(u,w);}
function frame(dir){const n=dir.clone().normalize(),ref=Math.abs(n.dot(UP))>.94?X:UP,u=new THREE.Vector3().crossVectors(n,ref).normalize(),v=new THREE.Vector3().crossVectors(n,u).normalize();return{n,u,v};}
function scaledPoint(p,sx,sy,sz=sx){return new THREE.Vector3(p[0]*sx,p[1]*sy,p[2]*sz);}
function curveBranch(id,order,points,r0,r1,parent=null){return{id,order,parent,curve:new THREE.CubicBezierCurve3(...points),radius0:r0,radius1:r1};}
function radiusAt(branch,t){return THREE.MathUtils.lerp(branch.radius0,branch.radius1,Math.pow(t,.82));}
function tube(out,b,scale=1,tMax=1){const samples=b.order===0?18:14,sides=b.order===0?9:7,base=out.positions.length/3;let last=null;for(let j=0;j<=samples;j++){const t=(j/samples)*tMax,p=b.curve.getPoint(t),tan=b.curve.getTangent(Math.min(.999,Math.max(.001,t)));let{u,v}=frame(tan);if(last&&u.dot(last)<0){u.multiplyScalar(-1);v.multiplyScalar(-1);}last=u.clone();const r=THREE.MathUtils.lerp(b.radius0,b.radius1,Math.pow(t,.78))*scale;for(let s=0;s<sides;s++){const a=s/sides*Math.PI*2,n=u.clone().multiplyScalar(Math.cos(a)).addScaledVector(v,Math.sin(a)),q=p.clone().addScaledVector(n,r*(1+.016*Math.sin(a*3+t*7)));vertex(out,q,n,.50+b.order*.022+t*.018);}}for(let j=0;j<samples;j++)for(let s=0;s<sides;s++){const a=base+j*sides+s,b0=base+j*sides+(s+1)%sides,c=base+(j+1)*sides+s,d=base+(j+1)*sides+(s+1)%sides;out.indices.push(a,c,b0,b0,c,d);}}
function atlasUV(tile,x,y){const z=.006;return[(tile+z+x*(1-z*2))/4,z+y*(1-z*2)];}
function plane(out,center,proxy,width,height,spin,tile,variation,tilt=0){const n=proxy.clone().normalize();let t=new THREE.Vector3().crossVectors(UP,n);if(t.lengthSq()<1e-7)t.copy(X);t.normalize();let b=new THREE.Vector3().crossVectors(n,t).normalize();const c=Math.cos(spin),s=Math.sin(spin),rt=t.clone().multiplyScalar(c).addScaledVector(b,s).normalize(),rb=b.clone().multiplyScalar(c).addScaledVector(t,-s).normalize();t=rt;b=rb;const physical=n.clone().multiplyScalar(1-Math.abs(tilt)).addScaledVector(t,tilt).normalize(),base=out.positions.length/3;for(const[x,y]of[[-.5,-.5],[.5,-.5],[.5,.5],[-.5,.5]]){const p=center.clone().addScaledVector(t,x*width).addScaledVector(b,y*height).addScaledVector(physical,Math.sin((x+y)*Math.PI)*width*.010),[u,v]=atlasUV(tile,x+.5,y+.5);vertex(out,p,n,variation,u,v);}out.indices.push(base,base+1,base+2,base,base+2,base+3);}
function inNegativeSpace(p,holes,sx,sy){for(const h of holes){const c=scaledPoint(h.center,sx,sy),rx=h.radius[0]*sx,ry=h.radius[1]*sy,rz=h.radius[2]*sx,d=((p.x-c.x)/rx)**2+((p.y-c.y)/ry)**2+((p.z-c.z)/rz)**2;if(d<1)return true;}return false;}
function buildAuthoredStructure(params,recipe,template){const growth=resolveGrowth(recipe,params.maturity),sx=(growth.spreadM/template.matureEnvelope.spreadM)*params.openness,sy=growth.heightM/template.matureEnvelope.heightM,branches=new Map(),visible=[];for(const spec of template.leaders){const rng=new RNG(hash(params.seed,spec.id)),pts=spec.points.map((p,i)=>scaledPoint(p,sx,sy).add(new THREE.Vector3(i===0?0:rng.signed(template.variation.branchControlM*sx),i===0?0:rng.signed(template.variation.branchControlM*sy),i===0?0:rng.signed(template.variation.branchControlM*sx))));const b=curveBranch(spec.id,0,pts,spec.radii[0]*THREE.MathUtils.lerp(.58,1,growth.maturity),spec.radii[1]*THREE.MathUtils.lerp(.58,1,growth.maturity));branches.set(b.id,b);visible.push(b);}for(const spec of template.scaffolds){const rng=new RNG(hash(params.seed,spec.id)),parent=branches.get(spec.parent),origin=parent.curve.getPoint(spec.attach),controls=spec.controls.map(p=>scaledPoint(p,sx,sy).add(new THREE.Vector3(rng.signed(template.variation.branchControlM*sx),rng.signed(template.variation.branchControlM*sy),rng.signed(template.variation.branchControlM*sx))));const startR=radiusAt(parent,spec.attach)*spec.radiusScale,b=curveBranch(spec.id,1,[origin,controls[0],controls[1],controls[2]],startR,startR*.32,parent.id);branches.set(b.id,b);visible.push(b);}return{growth,sx,sy,branches,visible};}

function buildRegionHierarchy(foliage,flowers,region,structure,params,template){const branch=structure.branches.get(region.branch),rng=new RNG(hash(params.seed,`hierarchy:${region.id}`)),center=branch.curve.getPoint(region.t).add(scaledPoint(region.offset,structure.sx,structure.sy)),jitter=1+rng.signed(template.variation.regionScale),size=new THREE.Vector3(region.size[0]*structure.sx*jitter,region.size[1]*structure.sy*jitter,region.size[2]*structure.sx*jitter),radii=size.clone().multiplyScalar(.5),toneBase={shadow:.455,mid:.505,light:.558}[region.tone],phase=rng.range(-Math.PI,Math.PI);let globalOut=new THREE.Vector3(center.x,0,center.z);if(globalOut.lengthSq()<1e-5)globalOut.copy(X);globalOut.normalize();const branchTangent=branch.curve.getTangent(region.t).normalize();let foundationCards=0,surfaceCards=0,accentCards=0,bloom=0;
  // Three very broad cross-oriented painted masses establish the region as one shape.
  for(let j=0;j<3;j++){const a=phase+j*(Math.PI*2/3),radial=new THREE.Vector3(Math.cos(a),rng.signed(.16),Math.sin(a)).normalize(),proxy=globalOut.clone().multiplyScalar(.38).addScaledVector(UP,.43).addScaledVector(radial,.25).addScaledVector(branchTangent,.10).normalize(),p=center.clone().add(new THREE.Vector3(Math.cos(a)*radii.x*.075,rng.signed(radii.y*.075),Math.sin(a)*radii.z*.075)),w=size.x*rng.range(.62,.78),h=size.y*rng.range(.67,.82),tone=toneBase+rng.signed(.003);if(!inNegativeSpace(p,template.negativeSpaces,structure.sx,structure.sy)){plane(foliage,p,proxy,w,h,a+rng.signed(.20),j%4,tone,rng.signed(.045));foundationCards++;}}
  // Medium cards live around the ellipsoid shell and break the foundation silhouette in true 3D.
  const count=Math.max(11,Math.round(region.planes*.55*Math.max(.65,params.density)));
  for(let i=0;i<count;i++){const y=1-2*(i+.5)/count,ring=Math.sqrt(Math.max(0,1-y*y)),a=i*GOLDEN+phase,dir=new THREE.Vector3(ring*Math.cos(a),y,ring*Math.sin(a)),shell=rng.range(.56,.92),p=center.clone().add(new THREE.Vector3(dir.x*radii.x*shell,dir.y*radii.y*shell,dir.z*radii.z*shell));if(inNegativeSpace(p,template.negativeSpaces,structure.sx,structure.sy))continue;const proxy=dir.clone().multiplyScalar(.48).addScaledVector(globalOut,.20).addScaledVector(UP,.38).addScaledVector(branchTangent,.08).normalize(),w=size.x*rng.range(.34,.47),h=size.y*rng.range(.48,.64),tone=toneBase+dir.y*.009+rng.signed(.004),tile=(i+Math.floor(rng.next()*4))%4;plane(foliage,p,proxy,w,h,rng.range(-Math.PI,Math.PI),tile,tone,rng.signed(.050));surfaceCards++;
    // Only a few smaller edge accents; enough to avoid a cookie-cutter boundary, not enough to become leaf noise.
    if(i%5===0&&Math.abs(dir.y)<.72){const edge=p.clone().addScaledVector(dir,rng.range(.035,.075)),ew=w*rng.range(.46,.58),eh=h*rng.range(.46,.60);plane(foliage,edge,proxy,ew,eh,rng.range(-Math.PI,Math.PI),(tile+1)%4,tone+rng.signed(.003),rng.signed(.045));accentCards++;}
    if(params.bloom>0&&region.tone!=='shadow'&&dir.y>.35&&rng.next()<.010*params.bloom){plane(flowers,p.clone().addScaledVector(proxy,.012),proxy,w*.19,h*.17,rng.range(-Math.PI,Math.PI),(tile+2)%4,.535,rng.signed(.025));bloom++;}}
  return{foundationCards,surfaceCards,accentCards,bloom};
}
function buildAuthoredCrown(structure,params,template){const foliage=bucket(),flowers=bucket();let foundationCards=0,surfaceCards=0,accentCards=0,flowerCount=0;for(const region of template.canopyRegions){const result=buildRegionHierarchy(foliage,flowers,region,structure,params,template);foundationCards+=result.foundationCards;surfaceCards+=result.surfaceCards;accentCards+=result.accentCards;flowerCount+=result.bloom;}return{foliage:geometry(foliage),flowers:geometry(flowers),foundationCards,surfaceCards,accentCards,masses:foundationCards+surfaceCards+accentCards,flowerCount};}

export function buildAuthoredVolumeDesertMuseum(params,recipe=DESERT_MUSEUM_PALO_VERDE,template=DESERT_MUSEUM_HERO_TEMPLATE){validateSpeciesRecipe(recipe);validateHeroTemplate(template);const structure=buildAuthoredStructure(params,recipe,template),wood=bucket(),outline=bucket();for(const b of structure.visible){tube(wood,b,1,b.order===0?1:.82);if(b.order===0)tube(outline,b,1.016,1);}const crown=buildAuthoredCrown(structure,params,template),wg=geometry(wood),og=geometry(outline),triangles=(wg.index.count+og.index.count+crown.foliage.index.count+crown.flowers.index.count)/3;if(triangles>recipe.lod0Budget.triangleHardCap)throw new Error(`LOD0 hard cap exceeded: ${triangles}`);return{wood:wg,outline:og,foliage:crown.foliage,flowers:crown.flowers,report:{schema:'threejs-palo-verde/5',recipeSchema:recipe.schema,recipeId:recipe.id,styleProfile:recipe.styleProfile,templateSchema:template.schema,templateId:template.id,seed:params.seed,maturity:params.maturity,targetHeightM:structure.growth.heightM,targetSpreadM:structure.growth.spreadM*params.openness,leaders:template.leaders.length,heroScaffolds:template.scaffolds.length,authoredCanopyRegions:template.canopyRegions.length,foliageMasses:crown.masses,foundationCards:crown.foundationCards,surfaceCards:crown.surfaceCards,accentCards:crown.accentCards,flowerBrushes:crown.flowerCount,triangles,triangleTarget:recipe.lod0Budget.triangleTarget,triangleHardCap:recipe.lod0Budget.triangleHardCap,lod:0,calendarCalibrated:false,authoredComposition:true,proceduralVariationBounded:true,regionClouds:true,hierarchicalCanopy:true,scaffoldVisibleFraction:.82,foliageRepresentation:'authored canopy regions built from broad foundation brush masses plus medium 3D surface breakup and sparse edge accents; continuous painted-cloud atlas with bent normals'}};}
