import * as THREE from 'three/webgpu';
import { DESERT_MUSEUM_PALO_VERDE, resolveGrowth, validateSpeciesRecipe } from './recipes.js';

const UP=new THREE.Vector3(0,1,0),X=new THREE.Vector3(1,0,0),GOLDEN=Math.PI*(3-Math.sqrt(5));
class RNG{constructor(seed=41){this.state=seed>>>0||1;}next(){let t=this.state+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;}range(a,b){return a+(b-a)*this.next();}signed(v=1){return this.range(-v,v);}int(a,b){return Math.floor(this.range(a,b+1));}}
function hs(seed,s){let h=seed>>>0;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619)>>>0;return h||1;}
function data(){return{positions:[],normals:[],variation:[],uv:[],indices:[]};}
function geometry(d){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(d.positions,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(d.normals,3));g.setAttribute('variation',new THREE.Float32BufferAttribute(d.variation,1));g.setAttribute('uv',new THREE.Float32BufferAttribute(d.uv,2));g.setIndex(d.indices);g.computeBoundingBox();g.computeBoundingSphere();return g;}
function basis(dir){const n=dir.clone().normalize(),ref=Math.abs(n.dot(UP))>.93?X:UP,u=new THREE.Vector3().crossVectors(n,ref).normalize(),v=new THREE.Vector3().crossVectors(n,u).normalize();return{n,u,v};}
function br(id,order,p0,p1,p2,p3,r0,r1,parent=null,leader=0){return{id,order,parent,leader,curve:new THREE.CubicBezierCurve3(p0,p1,p2,p3),radius0:r0,radius1:r1};}
function vertex(out,p,n,v,u=0,w=0){out.positions.push(p.x,p.y,p.z);out.normals.push(n.x,n.y,n.z);out.variation.push(v);out.uv.push(u,w);}
function tube(out,b,scale=1){const samples=b.order===0?16:b.order===1?11:8,sides=b.order===0?8:b.order===1?6:5,base=out.positions.length/3;let last=null;for(let j=0;j<=samples;j++){const t=j/samples,p=b.curve.getPoint(t),tan=b.curve.getTangent(Math.min(.999,Math.max(.001,t)));let{u,v}=basis(tan);if(last&&u.dot(last)<0){u.multiplyScalar(-1);v.multiplyScalar(-1);}last=u.clone();const radius=THREE.MathUtils.lerp(b.radius1,b.radius0,Math.pow(1-t,.72))*scale;for(let s=0;s<sides;s++){const a=s/sides*Math.PI*2,n=u.clone().multiplyScalar(Math.cos(a)).addScaledVector(v,Math.sin(a)),q=p.clone().addScaledVector(n,radius*(1+.018*Math.sin(a*3+t*8)));vertex(out,q,n,.54+b.order*.028+t*.024);}}for(let j=0;j<samples;j++)for(let s=0;s<sides;s++){const a=base+j*sides+s,b0=base+j*sides+(s+1)%sides,c=base+(j+1)*sides+s,d=base+(j+1)*sides+(s+1)%sides;out.indices.push(a,c,b0,b0,c,d);}}
function auv(tile,x,y){const z=.006;return[(tile+z+x*(1-z*2))/4,z+y*(1-z*2)];}
function plane(out,center,proxy,width,height,spin,tile,variation,tilt=0){const n=proxy.clone().normalize();let t=new THREE.Vector3().crossVectors(UP,n);if(t.lengthSq()<1e-7)t.copy(X);t.normalize();let b=new THREE.Vector3().crossVectors(n,t).normalize();const c=Math.cos(spin),s=Math.sin(spin),rt=t.clone().multiplyScalar(c).addScaledVector(b,s).normalize(),rb=b.clone().multiplyScalar(c).addScaledVector(t,-s).normalize();t=rt;b=rb;const physical=n.clone().multiplyScalar(1-Math.abs(tilt)).addScaledVector(t,tilt).normalize(),base=out.positions.length/3;for(const[x,y]of[[-.5,-.5],[.5,-.5],[.5,.5],[-.5,.5]]){const p=center.clone().addScaledVector(t,x*width).addScaledVector(b,y*height).addScaledVector(physical,Math.sin((x+y)*Math.PI)*width*.016),[u,v]=auv(tile,x+.5,y+.5);vertex(out,p,n,variation,u,v);}out.indices.push(base,base+1,base+2,base,base+2,base+3);}
function cluster(out,center,proxy,width,height,rng,tone,tile,layers=3){plane(out,center,proxy,width,height,rng.range(-Math.PI,Math.PI),tile,tone,rng.signed(.07));const{u,v}=basis(proxy);if(layers>1){const n2=proxy.clone().multiplyScalar(.82).addScaledVector(u,rng.next()<.5?.30:-.30).normalize();plane(out,center.clone().addScaledVector(proxy,rng.signed(width*.02)),n2,width*rng.range(.93,1.07),height*rng.range(.94,1.06),rng.range(-Math.PI,Math.PI),(tile+1+rng.int(0,2))%4,tone+rng.signed(.004),rng.signed(.08));}if(layers>2){const n3=proxy.clone().multiplyScalar(.84).addScaledVector(v,rng.next()<.5?.25:-.25).normalize();plane(out,center.clone().addScaledVector(proxy,rng.signed(width*.016)),n3,width*rng.range(.82,.98),height*rng.range(.82,1),rng.range(-Math.PI,Math.PI),(tile+2+rng.int(0,1))%4,tone+rng.signed(.004),rng.signed(.07));}}
function parentFrame(parent,t){const origin=parent.curve.getPoint(t),tan=parent.curve.getTangent(Math.min(.995,Math.max(.005,t))).normalize();let radial=new THREE.Vector3(origin.x,0,origin.z);if(radial.lengthSq()<1e-5)radial=new THREE.Vector3(tan.x,0,tan.z);if(radial.lengthSq()<1e-5)radial.copy(X);radial.normalize();return{origin,tan,radial,side:new THREE.Vector3().crossVectors(UP,radial).normalize()};}
function child(parent,id,order,t,length,sign,rng,rscale,up,out){const f=parentFrame(parent,t),dir=f.tan.clone().multiplyScalar(rng.range(.18,.34)).addScaledVector(f.side,sign*rng.range(.40,.72)).addScaledVector(f.radial,rng.range(out*.72,out*1.08)).addScaledVector(UP,rng.range(up*.72,up*1.10)).normalize(),end=f.origin.clone().addScaledVector(dir,length),p1=f.origin.clone().addScaledVector(f.tan,length*.16).addScaledVector(UP,length*.04),p2=f.origin.clone().lerp(end,.68).addScaledVector(f.side,sign*length*rng.range(.025,.065)).addScaledVector(UP,length*.035);return br(id,order,f.origin,p1,p2,end,parent.radius0*rscale*(1-t*.22),parent.radius1*rscale*.70,parent.id,parent.leader);}

function buildGraph(params,recipe){const growth=resolveGrowth(recipe,params.maturity),spread=growth.spreadM*params.openness,s=recipe.structure,branches=[],guides=[];for(let i=0;i<3;i++){const rng=new RNG(hs(params.seed,`stem:${i}`)),a=s.leaderAzimuth[i]+rng.signed(.13),stemH=THREE.MathUtils.lerp(growth.heightM*.56,s.leaderHeightMatureM[i],growth.maturity),p0=new THREE.Vector3(Math.cos(a)*.04,0,Math.sin(a)*.04),p3=new THREE.Vector3(Math.cos(a)*spread*s.leaderReachFraction[i],stemH,Math.sin(a)*spread*s.leaderReachFraction[i]),stem=br(`stem:${i}`,0,p0,new THREE.Vector3(Math.cos(a)*spread*.028,stemH*.35,Math.sin(a)*spread*.028),new THREE.Vector3(p3.x*.58+rng.signed(.10),p3.y*.76,p3.z*.58+rng.signed(.10)),p3,THREE.MathUtils.lerp(.068,.148,growth.maturity),THREE.MathUtils.lerp(.024,.056,growth.maturity),null,i);branches.push(stem);
 const scaffoldCount=4;for(let j=0;j<scaffoldCount;j++){const r=new RNG(hs(params.seed,`scaffold:${i}:${j}`)),t=.25+j*.205+r.signed(.014),len=spread*r.range(.29,.40)*(j===3?1.07:1),sign=(i+j)%2?-1:1,up=j===3?r.range(.42,.62):j===2?r.range(.28,.45):r.range(.18,.34),sc=child(stem,`scaffold:${i}:${j}`,1,t,len,sign,r,.54,up,.78);branches.push(sc);guides.push({branch:sc,kind:'scaffold'});
  const secCount=2+(j>1?1:0);for(let k=0;k<secCount;k++){const q=new RNG(hs(params.seed,`sec:${i}:${j}:${k}`)),bt=.34+k*(.48/Math.max(1,secCount-1))+q.signed(.018),sec=child(sc,`sec:${i}:${j}:${k}`,2,bt,len*q.range(.30,.44),(j+k)%2?-1:1,q,.45,q.range(.08,.24),.58);branches.push(sec);guides.push({branch:sec,kind:'secondary'});
   const w=new RNG(hs(params.seed,`twig:${i}:${j}:${k}`)),twig=child(sec,`twig:${i}:${j}:${k}`,3,w.range(.50,.69),len*w.range(.14,.22),w.next()<.5?-1:1,w,.38,w.range(.04,.16),.46);guides.push({branch:twig,kind:'twig'});
  }
 }
}return{growth,spread,height:growth.heightM,branches,guides};}

function guideFrame(b,t){const center=b.curve.getPoint(t),tan=b.curve.getTangent(Math.min(.995,t)).normalize(),{u,v}=basis(tan);let outward=new THREE.Vector3(center.x,0,center.z);if(outward.lengthSq()<1e-5)outward.copy(u);else outward.normalize();return{center,tan,u,v,outward,proxy:outward.clone().multiplyScalar(.46).addScaledVector(UP,.38).addScaledVector(tan,.16).normalize()};}
function buildCrown(graph,params,recipe){const foliage=data(),flowers=data(),avoid=recipe.growth.mature.spreadM*.18;let masses=0,accents=0,bloom=0,transition=0;for(const guide of graph.guides){const b=guide.branch,rng=new RNG(hs(params.seed,`fol:${b.id}`)),samples=guide.kind==='scaffold'?[.38,.50,.62,.73,.83,.92,.985]:guide.kind==='secondary'?[.34,.48,.62,.75,.87,.975]:[.55,.72,.88,.985];for(let si=0;si<samples.length;si++){const t=samples[si],f=guideFrame(b,t),yNorm=f.center.y/graph.height;if(yNorm<.24&&t<.65)continue;const tip=Math.pow(t,.72),upper=THREE.MathUtils.clamp((yNorm-.48)/.52,0,1),baseWidth=guide.kind==='scaffold'?rng.range(.62,.88):guide.kind==='secondary'?rng.range(.48,.72):rng.range(.34,.50),width=baseWidth*THREE.MathUtils.lerp(.78,1.20,tip)*THREE.MathUtils.lerp(1,1.18,upper),height=width*rng.range(.54,.74),count=guide.kind==='scaffold'?3:guide.kind==='secondary'?2:1,tone=.503+[-.003,0,.003][b.leader%3]+(upper-.5)*.008;
  for(let c=0;c<count;c++){const a=c*GOLDEN+rng.signed(.30),p=f.center.clone().addScaledVector(f.u,Math.cos(a)*width*rng.range(.05,.20)).addScaledVector(f.v,Math.sin(a)*width*rng.range(.04,.16)).addScaledVector(UP,rng.signed(width*.12)).addScaledVector(f.tan,(t>.85?1:-1)*rng.range(0,width*.08));if(Math.hypot(p.x,p.z)<avoid&&p.y>graph.height*.30)p.addScaledVector(f.outward,avoid*rng.range(.10,.25));cluster(foliage,p,f.proxy,width*(c?rng.range(.62,.82):1),height*(c?rng.range(.70,.88):1),rng,tone+rng.signed(.003),rng.int(0,3),3);masses++;}
  if(t<.72)transition++;
  if(t>.78&&rng.next()<.20){const aw=width*rng.range(.22,.32),ap=f.center.clone().addScaledVector(f.u,rng.signed(width*.16)).addScaledVector(UP,rng.signed(width*.10));plane(foliage,ap,f.proxy,aw,aw*rng.range(.36,.52),rng.range(-Math.PI,Math.PI),rng.int(0,3),tone+rng.signed(.004),rng.signed(.08));accents++;if(rng.next()<.05){plane(flowers,ap.clone().addScaledVector(UP,.016),f.proxy,aw*.36,aw*.22,rng.range(-Math.PI,Math.PI),rng.int(0,3),.52,rng.signed(.05));bloom++;}}
 }
}return{foliage:geometry(foliage),flowers:geometry(flowers),masses,accents,bloom,transition};}

export function buildDesertMuseum(params,recipe=DESERT_MUSEUM_PALO_VERDE){validateSpeciesRecipe(recipe);const graph=buildGraph(params,recipe),wood=data(),outline=data();for(const b of graph.branches){if(b.order<=2)tube(wood,b,1);if(b.order===0)tube(outline,b,1.018);}const crown=buildCrown(graph,params,recipe),wg=geometry(wood),og=geometry(outline),triangles=(wg.index.count+og.index.count+crown.foliage.index.count+crown.flowers.index.count)/3;if(triangles>recipe.lod0Budget.triangleHardCap)throw new Error(`LOD0 hard cap exceeded: ${triangles}`);return{wood:wg,outline:og,foliage:crown.foliage,flowers:crown.flowers,flowerCount:crown.bloom,report:{schema:'threejs-palo-verde/2',recipeSchema:recipe.schema,recipeId:recipe.id,styleProfile:recipe.styleProfile,seed:params.seed,maturity:params.maturity,targetHeightM:graph.height,targetSpreadM:graph.spread,branches:graph.branches.length,structuralBranches:graph.branches.length,microTwigs:0,foliageMasses:crown.masses,fineSprays:crown.accents,transitionMasses:crown.transition,foliageBrushes:crown.masses+crown.accents,flowerBrushes:crown.bloom,triangles,triangleTarget:recipe.lod0Budget.triangleTarget,triangleHardCap:recipe.lod0Budget.triangleHardCap,targetMet:triangles<=recipe.lod0Budget.triangleTarget,lod:0,calendarCalibrated:false,foliageRepresentation:'dense overlapping painted atlas clusters on branch-attached 3D guides with bent proxy normals'}};}
