import * as THREE from 'three/webgpu';
import { DESERT_MUSEUM_PALO_VERDE, resolveGrowth, validateSpeciesRecipe } from './recipes.js';
import { DESERT_MUSEUM_HERO_TEMPLATE, validateHeroTemplate } from './palo_verde_authored_template.js';

const UP=new THREE.Vector3(0,1,0),X=new THREE.Vector3(1,0,0),GOLDEN=Math.PI*(3-Math.sqrt(5));
class RNG{constructor(seed=41){this.state=seed>>>0||1;}next(){let t=this.state+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;}range(a,b){return a+(b-a)*this.next();}signed(v=1){return this.range(-v,v);}}
function hash(seed,label){let h=seed>>>0;for(let i=0;i<label.length;i++)h=Math.imul(h^label.charCodeAt(i),16777619)>>>0;return h||1;}
function bucket(){return{positions:[],normals:[],variation:[],uv:[],indices:[]};}
function geometry(d){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(d.positions,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(d.normals,3));g.setAttribute('variation',new THREE.Float32BufferAttribute(d.variation,1));g.setAttribute('uv',new THREE.Float32BufferAttribute(d.uv,2));g.setIndex(d.indices);g.computeBoundingBox();g.computeBoundingSphere();return g;}
function vertex(out,p,n,v,u=0,w=0){out.positions.push(p.x,p.y,p.z);out.normals.push(n.x,n.y,n.z);out.variation.push(v);out.uv.push(u,w);}
function frame(dir){const n=dir.clone().normalize(),ref=Math.abs(n.dot(UP))>.94?X:UP,u=new THREE.Vector3().crossVectors(n,ref).normalize(),v=new THREE.Vector3().crossVectors(n,u).normalize();return{n,u,v};}
function scaledPoint(p,sx,sy,sz=sx){return new THREE.Vector3(p[0]*sx,p[1]*sy,p[2]*sz);}
function curveBranch(id,order,points,r0,r1,parent=null){return{id,order,parent,curve:new THREE.CubicBezierCurve3(...points),radius0:r0,radius1:r1};}
function radiusAt(branch,t){return THREE.MathUtils.lerp(branch.radius0,branch.radius1,Math.pow(t,.82));}
function tube(out,b,scale=1,tMax=1){const samples=b.order===0?18:14,sides=b.order===0?9:7,base=out.positions.length/3;let last=null;for(let j=0;j<=samples;j++){const t=(j/samples)*tMax,p=b.curve.getPoint(t),tan=b.curve.getTangent(Math.min(.999,Math.max(.001,t)));let{u,v}=frame(tan);if(last&&u.dot(last)<0){u.multiplyScalar(-1);v.multiplyScalar(-1);}last=u.clone();const r=THREE.MathUtils.lerp(b.radius0,b.radius1,Math.pow(t,.78))*scale;for(let s=0;s<sides;s++){const a=s/sides*Math.PI*2,n=u.clone().multiplyScalar(Math.cos(a)).addScaledVector(v,Math.sin(a)),q=p.clone().addScaledVector(n,r*(1+.016*Math.sin(a*3+t*7)));vertex(out,q,n,.50+b.order*.022+t*.018);}}for(let j=0;j<samples;j++)for(let s=0;s<sides;s++){const a=base+j*sides+s,b0=base+j*sides+(s+1)%sides,c=base+(j+1)*sides+s,d=base+(j+1)*sides+(s+1)%sides;out.indices.push(a,c,b0,b0,c,d);}}
function atlasUV(tile,x,y){const z=.006;return[(tile+z+x*(1-z*2))/4,z+y*(1-z*2)];}
function plane(out,center,proxy,width,height,spin,tile,variation,tilt=0){const n=proxy.clone().normalize();let t=new THREE.Vector3().crossVectors(UP,n);if(t.lengthSq()<1e-7)t.copy(X);t.normalize();let b=new THREE.Vector3().crossVectors(n,t).normalize();const c=Math.cos(spin),s=Math.sin(spin),rt=t.clone().multiplyScalar(c).addScaledVector(b,s).normalize(),rb=b.clone().multiplyScalar(c).addScaledVector(t,-s).normalize();t=rt;b=rb;const physical=n.clone().multiplyScalar(1-Math.abs(tilt)).addScaledVector(t,tilt).normalize(),base=out.positions.length/3;for(const[x,y]of[[-.5,-.5],[.5,-.5],[.5,.5],[-.5,.5]]){const p=center.clone().addScaledVector(t,x*width).addScaledVector(b,y*height).addScaledVector(physical,Math.sin((x+y)*Math.PI)*width*.009),[u,v]=atlasUV(tile,x+.5,y+.5);vertex(out,p,n,variation,u,v);}out.indices.push(base,base+1,base+2,base,base+2,base+3);}
function inNegativeSpace(p,holes,sx,sy){for(const h of holes){const c=scaledPoint(h.center,sx,sy),rx=h.radius[0]*sx,ry=h.radius[1]*sy,rz=h.radius[2]*sx,d=((p.x-c.x)/rx)**2+((p.y-c.y)/ry)**2+((p.z-c.z)/rz)**2;if(d<1)return true;}return false;}
function buildAuthoredStructure(params,recipe,template){const growth=resolveGrowth(recipe,params.maturity),sx=(growth.spreadM/template.matureEnvelope.spreadM)*params.openness,sy=growth.heightM/template.matureEnvelope.heightM,branches=new Map(),visible=[];for(const spec of template.leaders){const rng=new RNG(hash(params.seed,spec.id)),pts=spec.points.map((p,i)=>scaledPoint(p,sx,sy).add(new THREE.Vector3(i===0?0:rng.signed(template.variation.branchControlM*sx),i===0?0:rng.signed(template.variation.branchControlM*sy),i===0?0:rng.signed(template.variation.branchControlM*sx))));const b=curveBranch(spec.id,0,pts,spec.radii[0]*THREE.MathUtils.lerp(.58,1,growth.maturity),spec.radii[1]*THREE.MathUtils.lerp(.58,1,growth.maturity));branches.set(b.id,b);visible.push(b);}for(const spec of template.scaffolds){const rng=new RNG(hash(params.seed,spec.id)),parent=branches.get(spec.parent),origin=parent.curve.getPoint(spec.attach),controls=spec.controls.map(p=>scaledPoint(p,sx,sy).add(new THREE.Vector3(rng.signed(template.variation.branchControlM*sx),rng.signed(template.variation.branchControlM*sy),rng.signed(template.variation.branchControlM*sx))));const startR=radiusAt(parent,spec.attach)*spec.radiusScale,b=curveBranch(spec.id,1,[origin,controls[0],controls[1],controls[2]],startR,startR*.32,parent.id);branches.set(b.id,b);visible.push(b);}return{growth,sx,sy,branches,visible};}

function addIrregularLobe(core,center,size,rng,tone,globalOut){const rings=5,sides=12,base=core.positions.length/3,rx=size.x*.40,ry=size.y*.40,rz=size.z*.40,phase=rng.range(-Math.PI,Math.PI),phase2=rng.range(-Math.PI,Math.PI);const normalBias=globalOut.clone().multiplyScalar(.23).addScaledVector(UP,.27).normalize();vertex(core,new THREE.Vector3(center.x,center.y+ry,center.z),new THREE.Vector3(0,1,0).lerp(normalBias,.24).normalize(),tone,.5,0);for(let i=1;i<rings;i++){const phi=Math.PI*i/rings,sp=Math.sin(phi),cp=Math.cos(phi);for(let j=0;j<=sides;j++){const theta=Math.PI*2*j/sides,wave=1+.080*Math.sin(theta*3+phase)*sp*sp+.042*Math.cos(theta*5-phi+phase2)*sp+.022*Math.sin(theta*7+phase2)*sp,local=new THREE.Vector3(Math.cos(theta)*sp*rx*wave,cp*ry*(1+.030*Math.sin(theta*3+phase)),Math.sin(theta)*sp*rz*wave),p=center.clone().add(local),n=new THREE.Vector3(local.x/(rx*rx),local.y/(ry*ry),local.z/(rz*rz)).normalize().multiplyScalar(.66).addScaledVector(normalBias,.34).normalize();vertex(core,p,n,tone+cp*.006,j/sides,i/rings);}}const bottom=core.positions.length/3;vertex(core,new THREE.Vector3(center.x,center.y-ry,center.z),new THREE.Vector3(0,-1,0).multiplyScalar(.55).addScaledVector(normalBias,.45).normalize(),tone,.5,1);for(let j=0;j<sides;j++)core.indices.push(base,base+1+j,base+2+j);for(let i=0;i<rings-2;i++){const start=base+1+i*(sides+1);for(let j=0;j<sides;j++){const a=start+j,b=a+sides+1;core.indices.push(a,b,a+1,a+1,b,b+1);}}const start=base+1+(rings-2)*(sides+1);for(let j=0;j<sides;j++)core.indices.push(start+j,bottom,start+j+1);}
function buildHybridRegion(core,edge,flowers,region,structure,params,template){const branch=structure.branches.get(region.branch),rng=new RNG(hash(params.seed,`sublobes:${region.id}`)),center=branch.curve.getPoint(region.t).add(scaledPoint(region.offset,structure.sx,structure.sy)),jitter=1+rng.signed(template.variation.regionScale),size=new THREE.Vector3(region.size[0]*structure.sx*jitter,region.size[1]*structure.sy*jitter,region.size[2]*structure.sx*jitter),toneBase={shadow:.455,mid:.505,light:.558}[region.tone];let globalOut=new THREE.Vector3(center.x,0,center.z);if(globalOut.lengthSq()<1e-5)globalOut.copy(X);globalOut.normalize();const tangent=branch.curve.getTangent(region.t).normalize(),{u,v}=frame(tangent),specs=[{scale:.72,offset:[0,0,0],tone:0},{scale:.58,offset:[.18,.10,.10],tone:.007},{scale:.55,offset:[-.16,.05,-.14],tone:-.006},{scale:.50,offset:[.07,-.14,.17],tone:-.010}];let coreLobes=0,edgeCards=0,bloom=0;
  specs.forEach((spec,index)=>{const s=size.clone().multiplyScalar(spec.scale*rng.range(.96,1.04)),p=center.clone().addScaledVector(u,spec.offset[0]*size.x).addScaledVector(UP,spec.offset[1]*size.y).addScaledVector(v,spec.offset[2]*size.z);if(inNegativeSpace(p,template.negativeSpaces,structure.sx,structure.sy))return;const outward=p.clone();outward.y=0;if(outward.lengthSq()<1e-5)outward.copy(globalOut);else outward.normalize();addIrregularLobe(core,p,s,new RNG(hash(params.seed,`${region.id}:core:${index}`)),toneBase+spec.tone,outward);coreLobes++;});
  const count=Math.max(3,Math.round(region.planes*.13*Math.max(.70,params.density))),radii=size.clone().multiplyScalar(.39),phase=rng.range(-Math.PI,Math.PI);for(let i=0;i<count;i++){const y=.68-1.12*(i+.5)/count,ring=Math.sqrt(Math.max(0,1-y*y)),a=i*GOLDEN+phase,dir=new THREE.Vector3(ring*Math.cos(a),y,ring*Math.sin(a)),p=center.clone().add(new THREE.Vector3(dir.x*radii.x,dir.y*radii.y,dir.z*radii.z));if(inNegativeSpace(p,template.negativeSpaces,structure.sx,structure.sy))continue;const proxy=dir.clone().multiplyScalar(.55).addScaledVector(globalOut,.18).addScaledVector(UP,.30).normalize(),w=size.x*rng.range(.17,.24),h=size.y*rng.range(.23,.33),tone=toneBase+dir.y*.008+rng.signed(.003),tile=(i+Math.floor(rng.next()*4))%4;plane(edge,p,proxy,w,h,rng.range(-Math.PI,Math.PI),tile,tone,rng.signed(.040));edgeCards++;if(params.bloom>0&&region.tone!=='shadow'&&dir.y>.38&&rng.next()<.012*params.bloom){plane(flowers,p.clone().addScaledVector(proxy,.012),proxy,w*.19,h*.18,rng.range(-Math.PI,Math.PI),(tile+2)%4,.535,rng.signed(.025));bloom++;}}return{coreLobes,edgeCards,bloom};}
function buildHybridCrown(structure,params,template){const core=bucket(),edge=bucket(),flowers=bucket();let coreLobes=0,edgeCards=0,flowerCount=0;for(const region of template.canopyRegions){const result=buildHybridRegion(core,edge,flowers,region,structure,params,template);coreLobes+=result.coreLobes;edgeCards+=result.edgeCards;flowerCount+=result.bloom;}return{core:geometry(core),edge:geometry(edge),flowers:geometry(flowers),coreRegions:template.canopyRegions.length,coreLobes,edgeCards,flowerCount};}

export function buildAuthoredVolumeDesertMuseum(params,recipe=DESERT_MUSEUM_PALO_VERDE,template=DESERT_MUSEUM_HERO_TEMPLATE){validateSpeciesRecipe(recipe);validateHeroTemplate(template);const structure=buildAuthoredStructure(params,recipe,template),wood=bucket(),outline=bucket();for(const b of structure.visible){tube(wood,b,1,b.order===0?1:.80);if(b.order===0)tube(outline,b,1.014,1);}const crown=buildHybridCrown(structure,params,template),wg=geometry(wood),og=geometry(outline),triangles=(wg.index.count+og.index.count+crown.core.index.count+crown.edge.index.count+crown.flowers.index.count)/3;if(triangles>recipe.lod0Budget.triangleHardCap)throw new Error(`LOD0 hard cap exceeded: ${triangles}`);return{wood:wg,outline:og,core:crown.core,foliage:crown.edge,flowers:crown.flowers,report:{schema:'threejs-palo-verde/7',recipeSchema:recipe.schema,recipeId:recipe.id,styleProfile:recipe.styleProfile,templateSchema:template.schema,templateId:template.id,seed:params.seed,maturity:params.maturity,targetHeightM:structure.growth.heightM,targetSpreadM:structure.growth.spreadM*params.openness,leaders:template.leaders.length,heroScaffolds:template.scaffolds.length,authoredCanopyRegions:template.canopyRegions.length,coreRegions:crown.coreRegions,coreLobes:crown.coreLobes,edgeCards:crown.edgeCards,foliageMasses:crown.coreLobes+crown.edgeCards,flowerBrushes:crown.flowerCount,triangles,triangleTarget:recipe.lod0Budget.triangleTarget,triangleHardCap:recipe.lod0Budget.triangleHardCap,lod:0,calendarCalibrated:false,authoredComposition:true,proceduralVariationBounded:true,hybridCanopy:true,clusteredOpaqueLobes:true,scaffoldVisibleFraction:.80,foliageRepresentation:'18 authored regions resolve to overlapping irregular opaque sub-lobes with coordinated tones plus very sparse painted edge cards; real hero scaffolds terminate inside canopy'}};}
